FROM node:22-alpine AS builder

WORKDIR /app
COPY package*.json ./
RUN npm ci

COPY . .
FROM node:22-alpine
ENV NODE_ENV=production

WORKDIR /app
RUN chown -R node:node /app
USER node
COPY --from=builder /app/package*.json ./
RUN npm ci --only=production && npm cache clean --force
COPY --from=builder /app .

EXPOSE 5000
CMD ["node", "server.js"]