spring:
  application:
    name: devlearn-backend

  datasource:
    url: jdbc:h2:mem:devlearndb  # ✅ Correct spelling
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true
      path: /h2-console

  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB

server:
  port: 8080

devlearn:
  upload-dir: ./uploads
  ai-service:
    url: http://localhost:5000
    timeout: 30000

logging:
  level:
    com.devlearn: DEBUG
    org.springframework.web: INFO