name: CI Basic Check

on:
  push:
    branches: [ "main", "dev", "feature/ci-cd" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Node 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Confirm placeholders exist
        run: |
          echo "Listing folders:"
          ls -la
          echo "frontend exists?"; [ -d frontend ] && echo "YES" || echo "NO"
          echo "backend exists?";  [ -d backend  ] && echo "YES" || echo "NO"

      - name: Secrets availability check (safe)
        run: |
          if [ -z "${{ secrets.DOCKER_USERNAME }}" ]; then
            echo "DOCKER_USERNAME not set"
          else
            echo "DOCKER_USERNAME exists"
          fi
          if [ -z "${{ secrets.DOCKER_PASSWORD }}" ]; then
            echo "DOCKER_PASSWORD not set"
          else
            echo "DOCKER_PASSWORD exists (value hidden)"
          fi